### ISSUE TITLE
Need to bump to a new bintray version number

### ISSUE THREAD

**Issue by stuhood** [pantsbuild/binaries#21]
The sync script is reporting that 0.0.5 is too old to be published to:
```
{"message":"Version '0.0.5' has been published more than 180 days ago and can no longer be deployed to."}
```

Bumping to a new version will mean reuploading anything we continue to want in bintray.

Rather than re-uploading absolutely everything, we might consider pruning the very oldest pre-1.0.0 binaries... or not? Thoughts?

**Comment by benjyw** [comment]
I think pruning is fine. In general, abandoning all support for Pants pre-1.0 seems totally fine to me.

We should, however, come up with a policy for when we EOL post 1.0 versions, but that's for another day.

**Comment by jsirois** [comment]
Bumping version does not mean what you think it does, they overlay. Bintray is weird.

**Comment by stuhood** [comment]
> Bumping version does not mean what you think it does, they overlay. Bintray is weird.

Aha, yep. Now bumped to `0.0.6`.
